[mypy]
files=**/*.py

# Specify the target platform details in config, so your developers are
# free to run mypy on Windows, Linux, or macOS and get consistent
# results.
python_version=3.8
platform=linux

# flake8-mypy expects the two following for sensible formatting
show_column_numbers=True
show_error_context=True

# do not follow imports (except for ones found in typeshed)
follow_imports=normal

# suppress errors about unsatisfied imports
ignore_missing_imports=True

# allow untyped calls as a consequence of the options above
disallow_untyped_calls=True

# allow returning Any as a consequence of the options above
warn_return_any=True

# treat Optional per PEP 484
strict_optional=True

# ensure all execution paths are returning
warn_no_return=True

# lint-style cleanliness for typing needs to be disabled; returns more errors
# than the full run.
warn_redundant_casts=True
warn_unused_ignores=False

# The following are off by default since they're too noisy.
# Flip them on if you feel adventurous.
disallow_untyped_defs=True
check_untyped_defs=True

# The warn_unused_configs flag may be useful to debug misspelled section names.
warn_unused_configs=True

[mypy-*.tests.*]
ignore_errors = True
